### ISSUE TITLE
Not working for certain .class files

### ISSUE THREAD

**Issue by swarnendubiswas** [gbalats/autodisass-java-bytecode#2]
The hook does not seem to work perfectly. The class file is from the lucene library. javap from the terminal works fine. Any ideas?

Here is a sample output:

����
����
����
����
����
���
���������
IS_INDEXED�B�
ConstantValue����STORE_TERMVECTOR����STORE_POSITIONS_WITH_TERMVECTOR����STORE_OFFSET_WITH_TERMVECTOR����
OMIT_NORMS����byNumber�Ljava/util/ArrayList;�byName�Ljava/util/HashMap;�<init>�()V�Code�LineNumberTable�LocalVariableTable�this�$Lorg/apache/lucene/index/FieldInfos;�8(Lorg/apache/lucene/store/Directory;Ljava/lang/String;)V�d�#Lorg/apache/lucene/store/Directory;�name�Ljava/lang/String;�input�$Lorg/apache/lucene/store/IndexInput;�
Exceptions���add�((Lorg/apache/lucene/document/Document;)V�field�"Lorg/apache/lucene/document/Field;�doc�%Lorg/apache/lucene/document/Document;�fields�Ljava/util/Enumeration;�

**Comment by gbalats** [comment]
Can you provide a link to the exact version of the lucene library that is failing, and the name of the class file?

**Comment by swarnendubiswas** [comment]
Actually my class file is from a benchmark called luindex in the DaCapo 2009 benchmark suite, which is used for Java benchmarking. I have placed an example class file here: http://web.cse.ohio-state.edu/~biswass/files/FieldInfos.class. 

You can disassemble with "javap -c -p", and the result is legible. But opening with autodisassemble package does not work. I tried with javap-mode but that doesn't work either.

**Comment by gbalats** [comment]
I'm having trouble reproducing the error. The downloaded class file is disassembled without any problems on my system.

Also, I tried the original dacapo bach jar. I ran the luindex benchmark so that the relevant jars are extracted, and then opened the lucene-core-2.4.jar and the FieldInfos class therein. Again, it worked fine.

Does this behavior occur only when trying to open the class file inside a jar, or even with the extracted class file?

**Comment by swarnendubiswas** [comment]
I have actually built the DaCapo benchmarks source code with eclipse. I face this issue while opening those .class files present in eclipse /bin directory. 

I tried opening the .class file I shared from another emacs installation (24.3), and I have the same problem, it still shows junk. Do you need any other packages for this to work? I have attached a screenshot to show the problem. 
![screenshot from 2015-02-09 22 02 04](https://cloud.githubusercontent.com/assets/7343807/6120752/962a853a-b0a7-11e4-802d-5842c4eb456a.png)

**Comment by biboudis** [comment]
This happens to me as well. I have emacs 24.

e.g., 

![screenshot from 2015-10-05 18 17 48](https://cloud.githubusercontent.com/assets/765983/10284589/6d7001aa-6b8d-11e5-8405-5b6dd1bb5e3c.png)

**Comment by gbalats** [comment]
Probably the buffer you see was the one produced by `javap-mode`, which tries to disassemble the file as well. I stopped using it as a dependency and simply copied the code fragment useful for highlighting.

The MELPA version is now updated, so could you check if the error persists after updating your packages?

**Comment by biboudis** [comment]
Still does.

**Comment by biboudis** [comment]
Ok, it works by deleting javap-mode. 

@swarnendubiswas I updated autodisass and I deleted javap-mode. Try that if it works for you as well.

Thx @gbalats.

**Comment by swarnendubiswas** [comment]
Thanks for the updates, but it still does not work for me for the .class file I had attached earlier.

**Comment by biboudis** [comment]
Even after deleting javap-mode?

**Comment by gbalats** [comment]
@swarnendubiswas you could clone the repo and modify the code of `ad-java-bytecode-buffer` to add a call to `message` that prints the arguments of `apply` (before calling `apply`). This way you can see exactly what command is being executed (and hopefully why it does not work).

**Comment by swarnendubiswas** [comment]
Okay, now it works. I am actually using [use-package](https://github.com/jwiegley/use-package) to manage by init files, and had a `:defer t`. I will close the issue. Thanks for the update.

@gbalats  Just curious, how does this package exactly differ from `javap` and `javap-mode`?

**Comment by gbalats** [comment]
The main difference is that it also works for jars. So, you can open a jar through emacs and then select a class file entry, and it will be automatically disassembled. No need to unzip the jar first.
